### PR TITLE
feat(release): allow github oidc auth provider for aws code artifact

### LINKED ISSUE #1313: Support ephemeral credentials in codeArtifactOptions of CDK construct libs
Today, it seems like projen supports doing an assumeRole call, but only after it has used persistent IAM user credentials to do so. Instead, I'd prefer to see this support ephemeral creds from the get-go. 

~A simple stop-gap solution might be to accept a `sessionToken` parameter as an optional input.~ 

EDIT: Projen really only looks for Github secret keys and won't accept env vars set elsewhere. Though maybe it doesn't need to look for them? I dug through the source and saw it's deferring to jsii-release. ~Based on the code here, maybe this would just work out of the box by defaulting to env vars? https://github.com/cdklabs/jsii-release/blob/master/bin/jsii-release-npm#L23-L34~

EDIT AGAIN: Seems like there are some issues that block usage of ephemeral credentials. See comments below for details.

It'd be nice if the docs nudged people to using the new OIDC feature for federating Github to AWS: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Right now, this is the interface:

```typescript
/**
 * @experimental
 */
export interface CodeArtifactOptions {
    /**
     * (experimental) GitHub secret which contains the AWS access key ID to use when publishing packages to AWS CodeArtifact.
     *
     * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
     *
     * @default "AWS_ACCESS_KEY_ID"
     * @experimental
     */
    readonly accessKeyIdSecret?: string;
    /**
     * (experimental) GitHub secret which contains the AWS secret access key to use when publishing packages to AWS CodeArtifact.
     *
     * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
     *
     * @default "AWS_SECRET_ACCESS_KEY"
     * @experimental
     */
    readonly secretAccessKeySecret?: string;
    /**
     * (experimental) ARN of AWS role to be assumed prior to get authorization token from AWS CodeArtifact This property must be specified only when publishing to AWS CodeArtifact (`registry` contains AWS CodeArtifact URL).
     *
     * @default undefined
     * @experimental
     */
    readonly roleToAssume?: string;
}
```

### PR DESCRIPTION
**Pull request by bilalq**
### Summary 
This closes #1313.

Empehmeral credentials are more secure than fixed ones. Prior to this change, users had to have fixed secrets defined in Github for an AWS access/secret key pair to publish to CodeArtifact. With this change, it is now possible to use Github's OIDC provider to assume a role without the need for any long-lived credentials.

Backwards compatibility is preserved and all existing users will be unaffected unless they explicitly update the `authProvider` of `codeArtifactOptions` to `GITHUB_OIDC`.

### Background Context

The `codeArtifactOptions` property affects the generated release github workflow for publishing  to npm. This workflow installs dependencies, builds artifacts, and then delegates to [publib](https://github.com/cdklabs/publib) for the actual publishing logic. 

This is the relevant excerpt from generated code prior to the changes from this PR:

```yaml
- name: Release
  run: npx -p publib@latest publib-npm
  env:
    NPM_DIST_TAG: latest
    NPM_REGISTRY: example-123456789012.d.codeartifact.us-east-2.amazonaws.com/example-domain/example-repo/
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_ROLE_TO_ASSUME: arn:aws:iam::123456789012:role/example-role
```

And [this is the relevant excerpt from publib for generation of the `NPM_TOKEN`](https://github.com/cdklabs/publib/blob/main/bin/publib-npm#L24-L40):

```bash
if ! [ -z "${NPM_REGISTRY:-}" ] && [[ $NPM_REGISTRY =~ .codeartifact.*.amazonaws.com ]]; then
  codeartifact_account="$(echo $NPM_REGISTRY | cut -d. -f1 | rev | cut -d- -f1 | rev)"
  codeartifact_subdomain="$(echo $NPM_REGISTRY | cut -d. -f1)"
  codeartifact_domain="$(echo $codeartifact_subdomain | cut -b -$((${#codeartifact_subdomain}-${#codeartifact_account}-1)))"
  codeartifact_region="$(echo $NPM_REGISTRY | cut -d. -f4)"
  export AWS_DEFAULT_REGION="$(echo $codeartifact_region)" 
  if [ -n "${AWS_ROLE_TO_ASSUME:-}" ]; then
    credentials=`aws sts assume-role --role-session-name "publib-code-artifact" --role-arn ${AWS_ROLE_TO_ASSUME} --output text | sed -n '2 p'`
    export AWS_ACCESS_KEY_ID="$(echo $credentials | cut -d' ' -f2)"
    export AWS_SECRET_ACCESS_KEY="$(echo $credentials | cut -d' ' -f4)"
    export AWS_SESSION_TOKEN="$(echo $credentials | cut -d' ' -f5)"
  fi
  NPM_TOKEN=`aws codeartifact get-authorization-token --domain $codeartifact_domain --domain-owner $codeartifact_account --region $codeartifact_region --query authorizationToken --output text`
elif [ -z "${NPM_TOKEN:-}" ]; then
  echo "NPM_TOKEN is required"
  exit 1
fi
```

We can see that if the `AWS_ROLE_TO_ASSUME` environment variable is defined, it will make a call to STS to fetch credentials. Otherwise, it will just use whatever the default aws provider resolves to. Prior to this change, that would have it read from the access/secret key env variables that get set.

### Interface Changes

Previously, the interface for CodeArtifactOptions looked like this:

```typescript
export interface CodeArtifactOptions {
  /**
   * GitHub secret which contains the AWS access key ID to use when publishing packages to AWS CodeArtifact.
   * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
   *
   * @default "AWS_ACCESS_KEY_ID"
   */
  readonly accessKeyIdSecret?: string;

  /**
   * GitHub secret which contains the AWS secret access key to use when publishing packages to AWS CodeArtifact.
   * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
   *
   * @default "AWS_SECRET_ACCESS_KEY"
   */
  readonly secretAccessKeySecret?: string;

  /**
   * ARN of AWS role to be assumed prior to get authorization token from AWS CodeArtifact
   * This property must be specified only when publishing to AWS CodeArtifact (`registry` contains AWS CodeArtifact URL).
   *
   * @default undefined
   */
  readonly roleToAssume?: string;
}
```

After this change, they now look like:

```typescript
/**
 * Options for authorizing requests to a AWS CodeArtifact npm repository.
 */
export enum CodeArtifactAuthProvider {
  /**
   * Fixed credentials provided via Github secrets.
   */
  ACCESS_AND_SECRET_KEY_PAIR = "ACCESS_AND_SECRET_KEY_PAIR",

  /**
   * Ephemeral credentials provided via Github's OIDC integration with an IAM role.
   * See:
   * https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html
   * https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
   */
  GITHUB_OIDC = "GITHUB_OIDC",
}

/**
 * Options for publishing packages to AWS CodeArtifact.
 */
export interface CodeArtifactOptions {
  /**
   * Provider to use for authorizing requests to AWS CodeArtifact.
   *
   * @default CodeArtifactAuthProvider.ACCESS_AND_SECRET_KEY_PAIR
   */
  readonly authProvider?: CodeArtifactAuthProvider;

  /**
   * GitHub secret which contains the AWS access key ID to use when publishing packages to AWS CodeArtifact.
   * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
   *
   * @default - When the `authProvider` value is set to
   * `CodeArtifactAuthProvider.ACCESS_AND_SECRET_KEY_PAIR`, the default is
   * "AWS_ACCESS_KEY_ID". For `CodeArtifactAuthProvider.GITHUB_OIDC`, this
   * value must be left undefined.
   */
  readonly accessKeyIdSecret?: string;

  /**
   * GitHub secret which contains the AWS secret access key to use when publishing packages to AWS CodeArtifact.
   * This property must be specified only when publishing to AWS CodeArtifact (`npmRegistryUrl` contains AWS CodeArtifact URL).
   *
   * @default - When the `authProvider` value is set to
   * `CodeArtifactAuthProvider.ACCESS_AND_SECRET_KEY_PAIR`, the default is
   * "AWS_SECRET_ACCESS_KEY". For `CodeArtifactAuthProvider.GITHUB_OIDC`, this
   * value must be left undefined.
   */
  readonly secretAccessKeySecret?: string;

  /**
   * ARN of AWS role to be assumed prior to get authorization token from AWS CodeArtifact
   * This property must be specified only when publishing to AWS CodeArtifact (`registry` contains AWS CodeArtifact URL).
   * When using the `CodeArtifactAuthProvider.GITHUB_OIDC` auth provider, this value must be defined.
   *
   * @default undefined
   */
  readonly roleToAssume?: string;
}
```

### Behavior Changes

This change preserves backwards compatibility and allows for users to optionally specify an `authProvider` property. It defaults to access/secret key pair based auth if not explicitly defined. 

If the value is set to `GITHUB_OIDC`, then the generated Github release workflow changes. Credentials get set using the [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) github action. Note that this involves a change to the workflow's permissions.

As before, given the following projenrc config:

```typescript
{
  // ...
  npmRegistryUrl: 'https://example-123456789012.d.codeartifact.us-east-2.amazonaws.com/example-domain/example-repo/',
  codeArtifactOptions: {
    // accessKeyIdSecret can be omitted, but defaults to 'AWS_ACCESS_KEY_ID'
    // secretAccessKeySecret can be omitted, but defaults to 'AWS_SECRET_ACCESS_KEY'
    roleToAssume: 'arn:aws:iam::123456789012:role/example-role'
  }
}
```

The generated github job looks like:

```yaml
release_npm:
  name: Publish to npm
  needs: release
  runs-on: ubuntu-latest
  permissions:
    contents: read
  if: needs.release.outputs.latest_commit == github.sha
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: dist
    - name: Prepare Repository
      run: mv dist .repo
    - name: Install Dependencies
      run: cd .repo && npm ci
    - name: Create js artifact
      run: cd .repo && npx projen package:js
    - name: Collect js Artifact
      run: mv .repo/dist dist
    - name: Release
      run: npx -p publib@latest publib-npm
      env:
        NPM_DIST_TAG: latest
        NPM_REGISTRY: example-123456789012.d.codeartifact.us-east-2.amazonaws.com/example-domain/example-repo/
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ROLE_TO_ASSUME: arn:aws:iam::123456789012:role/example-role
```

But if you specify the authProvider as `GITHUB_OIDC`:

```typescript
{
  // ...
  npmRegistryUrl: 'https://example-123456789012.d.codeartifact.us-east-2.amazonaws.com/example-domain/example-repo/',
  codeArtifactOptions: {
    authProvider: CodeArtifactAuthProvider.GITHUB_OIDC,
    roleToAssume: 'arn:aws:iam::123456789012:role/example-role'
  }
}
```

The generated workflow now looks like:

```yaml
release_npm:
  name: Publish to npm
  needs: release
  runs-on: ubuntu-latest
  permissions:
    id-token: write
    contents: read
  if: needs.release.outputs.latest_commit == github.sha
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: dist
    - name: Configure AWS Credentials via GitHub OIDC Provider
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::123456789012:role/example-role
        aws-region: us-east-2
    - name: Release
      run: npx -p publib@latest publib-npm
      env:
        NPM_DIST_TAG: latest
        NPM_REGISTRY: example-123456789012.d.codeartifact.us-east-2.amazonaws.com/example-domain/example-repo/

```

The delegation to publib happens as before, but now with credentials set by the [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) github action. Note the additional `id-token: write` permission, the added configure-aws-credentials step, and the omission of the `AWS_ROLE_TO_ASSUME` environment variable for the publib step.

### Testing Done

I've tried creating a new projen project and running the linked `pj` alias and verified that the generated code looks as expected. `yarn test`, `yarn build`, and `yarn eslint` all pass. I have not verified that publib's CLI call to CodeArtifact works as expected, but I believe it should. 

### Concerns for Reviewers

I'm not terribly happy with the duplication of enums and interfaces going on. It forces enum to enum mappings and duplication of validation logic. This would be less painful using However that was what the codebase was doing prior this change, so I assumed there was some good reason and kept that approach.

One problem is that the duplication of the enum results in duplicate intellisense suggestions. Would you the maintainers be okay with me not duplicating the enum? And if so, which location would be preferred? The `publisher.ts` one, maybe?
 
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — CHANGES_REQUESTED** [review]
@bilalq This looks great! Thanks for implementing this. I agree with deduplicating `CodeArtifactOptions` interface and I agree that they should live in the publisher. Would you mind making that change? Otherwise I'm happy to merge it as is as well.

What we definitely should add however is a user guide. I think you've already written most of it in the PR description & doc strings. The relevant section of the guide is here:
https://github.com/projen/projen/blob/main/docs/publisher.md#publishing-to-aws-codeartifact

**Review by mrgrain — APPROVED** [review]
Refactoring can be done later.

**Comment by bilalq** [comment]
@mrgrain Sorry, I meant to comment this earlier, but have been busy.

I got held up on the refactor when I noticed that this current implementation while this implementation does handle publishing to code artifact, it doesn't handle the case of requiring dependencies that are from code artifact. The [`getScopedPackageSteps`](https://github.com/projen/projen/blob/c6048af0bfa35c7be015e926eae9dd9f5aafd28f/src/javascript/node-project.ts#L800) is used for that purpose. 


This PR doesn't break backwards compatibility, so everything still works as expected, it's just you can't use ephemeral creds to require deps that are from codeartifact in the current state.


I was able to make the changes needed for most of this, but ran into a bit of a hurdle with the permissions of the generated Github workflow. [I can generate the correct steps in the job, but there isn't an easy way to bubble up the needed permissions](https://github.com/projen/projen/blob/c6048af0bfa35c7be015e926eae9dd9f5aafd28f/src/javascript/node-project.ts#L857-L864). In this case, it'd be `write` access to the `id-token` Github permission. 

The easy way to address this is to just always have the generated workflows have write permission to `id-token` the way they always have write permission to `contents`. If we want to do it selectively, then I'd probably turn to the maintainers for guidance on how that should be achieved.

**Comment by mrgrain** [comment]
Thanks for calling this out! 

I reckon we can give [`BuildWorkflowOptions` ](https://github.com/projen/projen/blob/15399b13c6d6de6f85738c6c113d338d0c74134f/src/build/build-workflow.ts#L31)a new option permissions, which are then included in `addBuildJob`:
https://github.com/projen/projen/blob/15399b13c6d6de6f85738c6c113d338d0c74134f/src/build/build-workflow.ts#L159-L161

In the `NodeProject` we can conditionally add these extra permissions if the OIDC is configured.
https://github.com/projen/projen/blob/c6048af0bfa35c7be015e926eae9dd9f5aafd28f/src/javascript/node-project.ts#L518-L530

**Pull request merged**
