### PR TITLE
feat(node-package): added bun as a package manager

### PR DESCRIPTION
**Pull request by Liam-Johnston**
Adding the ability to select bun as the package manage for a node based project.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
Hey thanks for that. This will need a few more changes to actually use bun though. Can you add them?

**Comment by Liam-Johnston** [comment]
@mrgrain yup I'll take a look when I get a chance :)

**Comment by Liam-Johnston** [comment]
@mrgrain Changes made! Please let me know what you think when you get a chance :)

**Comment by mrgrain** [comment]
Nice! Although the irony that **Node**Package supports **Bun** 😂

**Comment by Liam-Johnston** [comment]
HAhahahahaha

**Comment by Liam-Johnston** [comment]
Sorry @mrgrain seems I didn't run a build locally before!

Could you please review again so the build can kick off :)

**Pull request merged**
