### PR TITLE
fix(file): incorrect projen command in markers

### PR DESCRIPTION
**Pull request by tinovyatkin**
Currently projen marker contains hard coded command to run projen `npx projen`.  However, it's not always the right command, particularly it looks completely wrong in JSII projects (such as Python). This PR fixes that by using proper existing `projenCommand` field in markers.

On side case of this change is generated files for projen itself, so this PR includes seconds commit with updates to to such files generated as result of `yarn build`

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — CHANGES_REQUESTED** [review]
This looks good. When I experimented with this I came across a scenario where it didn't work. I'll need to dig that out to remind myself.

**Review by mrgrain — APPROVED** [review]
Approving. I think I just didn't like what this does to this repo. But it's actually accurate.

**Comment by tinovyatkin** [comment]
@mrgrain label is blocking merge?

**Comment by mrgrain** [comment]
> @mrgrain label is blocking merge?

Ah and the mergify config has changed, so I need to click the button manually. 🤦‍♂️

**Pull request merged**
