### PR TITLE
fix(nextjs-ts): starter project fails to build with projenrc.ts

### LINKED ISSUE #1463: react-ts: Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension
Seems like projen stops working within the `react-ts` and `.projenrc.ts` setup:

```
❯ pj
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
(node:24305) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
xyz/projen-react/.projenrc.ts:1
import { web, TextFile } from "projen";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Module.m._compile (xyz/projen-react/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.require.extensions.<computed> [as .ts] (xyz/projen-react/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at main (xyz/projen-react/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (xyz/projen-react/node_modules/ts-node/src/bin.ts:288:3)
👾 Synthesis failed: Task "default" failed when executing "ts-node --project tsconfig.dev.json .projenrc.ts" (cwd: xyz/projen-react)
```

### PR DESCRIPTION
**Pull request by pgollucci**
fixes #1463

### CODE REVIEW

**Comment by pgollucci** [comment]
There are other downstream issues like eslint, incremental, js vs json, and too much stoff being in or out of rootDir or pages.

**Comment by Chriscbr** [comment]
I'm not sure if this fixes the linked issue. [This comment](https://github.com/projen/projen/issues/1463#issuecomment-1008050362) says that we need to change tsconfig.dev.json, not tsconfig.json.

**Comment by pgollucci** [comment]
@Chriscbr actually it does. It does both. Look at the diff of the snap test.  You'll need to click on the view file to see the scopes.

**Comment by pgollucci** [comment]
@Mergifyio rebase

**Review by Chriscbr — APPROVED** [review]
@pgollucci Ah, I'm duly mistaken. Thanks for the fix!

**Comment by doyasu24** [comment]
> The same error occurs when the following commands
> - `npx projen new nextjs-ts --projenrc-ts`
> - `yarn projen`
https://github.com/projen/projen/issues/1463#issuecomment-1008050362

I tried these commands again and confirmed that the issue was fixed.
Thank you!

**Pull request merged**
