### PR TITLE
fix: codeartifact fixes wip

### PR DESCRIPTION
**Pull request by devnoo**
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by devnoo** [comment]
I tested the ca:login adjustments, release is difficult to test for me, but that should normally work

**Comment by mrgrain** [comment]
Drafting this while it's WIP. Just makes my life a little bit easier. You can mark as "Ready for Review" whenever you're happy with it.

**Comment by devnoo** [comment]
@mrgrain i'm having some trouble to get the last part to work. 
in the jssi project's pacmakForLanguage, when you have set scoped packageOptions, you would also need the steps that the node project generates when using codeartifact.

Bit difficult to hack them in now, seeing method returns Jobstep vs step , is private, .
Any advise ?

**Comment by devnoo** [comment]
`diff --git a/node_modules/projen/lib/cdk/jsii-project.js b/node_modules/projen/lib/cdk/jsii-project.js
index c9ee619..907f9ef 100644
--- a/node_modules/projen/lib/cdk/jsii-project.js
+++ b/node_modules/projen/lib/cdk/jsii-project.js
@@ -249,6 +249,11 @@ class JsiiProject extends typescript_1.TypeScriptProject {
                 with: { version: this.package.pnpmVersion },
             });
         }
+
+        if (this.package.codeArtifactOptions){
+            prePublishSteps.push(...this.getScopedPackageSteps(this.package.codeArtifactOptions))
+      
+        }
         prePublishSteps.push({
             name: "Prepare Repository",
             run: `mv ${this.artifactsDirectory} ${REPO_TEMP_DIRECTORY}`,
diff --git a/node_modules/projen/lib/javascript/node-package.js b/node_modules/projen/lib/javascript/node-package.js
index 81edbc2..17babd5 100644
--- a/node_modules/projen/lib/javascript/node-package.js
+++ b/node_modules/projen/lib/javascript/node-package.js
@@ -495,18 +495,16 @@ class NodePackage extends component_1.Component {
             return;
         }
         this.project.addTask("ca:login", {
-            requiredEnv: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
+            // requiredEnv: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"],
             steps: [
                 { exec: "which aws" },
                 ...this.scopedPackagesOptions.map((scopedPackagesOption) => {
                     const { registryUrl, scope } = scopedPackagesOption;
-                    const { domain, region, accountId, registry } = (0, util_1.extractCodeArtifactDetails)(registryUrl);
+                    const { domain, region, accountId, registry , repository} = (0, util_1.extractCodeArtifactDetails)(registryUrl);
                     // reference: https://docs.aws.amazon.com/codeartifact/latest/ug/npm-auth.html
                     const commands = [
-                        `npm config set ${scope}:registry ${registryUrl}`,
-                        `CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${domain} --region ${region} --domain-owner ${accountId} --query authorizationToken --output text)`,
-                        `npm config set //${registry}:_authToken=$CODEARTIFACT_AUTH_TOKEN`,
-                        `npm config set //${registry}:always-auth=true`,
+                        `aws codeartifact login --region ${region}  --tool npm --repository ${repository}  --domain ${domain} --domain-owner ${accountId}`,
+                        `npm config set always-auth=true`,
                     ];
                     return {
                         exec: commands.join("; "),
diff --git a/node_modules/projen/lib/release/publisher.js b/node_modules/projen/lib/release/publisher.js
index 8e6a8a0..ff80c09 100644
--- a/node_modules/projen/lib/release/publisher.js
+++ b/node_modules/projen/lib/release/publisher.js
@@ -163,6 +163,11 @@ class Publisher extends component_1.Component {
                     "aws-region": region,
                 },
             });
+
+            prePublishSteps.push({
+                name: "Configure AWS CodeArtifact",
+                run: "npx projen ca:login"
+            })
         }
         this.addPublishJob((_branch, branchOptions) => {
             if (branchOptions.npmDistTag && options.distTag) {
`

patch created with patch-package that made the whole process work for me

**Comment by mrgrain** [comment]
@devnoo Thanks for your work so far. I'll have a look as soon as possible.

**Comment by mrgrain** [comment]
stale

**Pull request closed without merging**
