### PR TITLE
fix(release): artifact permissions are not preserved in github actions

### LINKED ISSUE #2103: Projen python version default command fails
Hello, guys, thank you for the awesome tool, the nodejs version works perfectly, however, I'm struggling with the Python binary. Simply installed it globally using `pipx install projen` and running `projen`, fails with the following error:
```sh
➜  ~ projen
Traceback (most recent call last):
  File "/Users/victor/.local/bin/projen", line 10, in <module>
    __jsii_assembly__.invokeBinScript("projen", "projen", sys.argv[1:])
  File "/Users/victor/.local/pipx/venvs/projen/lib/python3.10/site-packages/jsii/_runtime.py", line 52, in invokeBinScript
    response = _kernel.invokeBinScript(pkgname, script, args)
  File "/Users/victor/.local/pipx/venvs/projen/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 312, in invokeBinScript
    args=_make_reference_for_native(self, args),
  File "/Users/victor/.local/pipx/venvs/projen/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 204, in _make_reference_for_native
    kernel.create(d.__class__, d)
  File "/Users/victor/.local/pipx/venvs/projen/lib/python3.10/site-packages/jsii/_kernel/__init__.py", line 323, in create
    fqn=klass.__jsii_type__ or "Object",
AttributeError: type object 'tuple' has no attribute '__jsii_type__'
```
I tried py3.8 and py3.10, and encounter the same result. weird that there is no such issue yet, I'm the only one having this error?
Thank you for your help.

### PR DESCRIPTION
**Pull request by jmalins**
Fixes #2103.

Due to a bug in GitHub actions, file mode permissions (such as `+x`) are lost between when the build artifact is uploaded at the end of the build job and download in each release job. This results in the published artifact tarballs having incorrect permissions. The main user impact is that bin scripts are no longer executable. NPM automatically fixes this during install, but other JSII toolchains, such as Python, do not.

See details of GitHub Actions bug [here](https://github.com/actions/upload-artifact/issues/38).

To workaround the issue, this PR backs up the permissions of the artifact tree to a file (`permissions-backup.acl`) prior to upload, then restores them after download using the Linux `getfacl` and `setfacl` CLI tools.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jmalins** [comment]
Verified that the `+x` permission is added using a modified workflow (with `ls` statements) on my local fork.
```
Run cd dist && ls -la bin && setfacl --restore=permissions-backup.acl && ls -la bin
total 12
drwxr-xr-x  2 runner docker [4](https://github.com/jmalins/projen/actions/runs/3154813439/jobs/5132887862#step:4:5)096 Sep 29 21:55 .
drwxr-xr-x 17 runner docker 4096 Sep 29 21:55 ..
-rw-r--r--  1 runner docker  118 Sep 29 21:55 projen
total 12
drwxr-xr-x  2 runner docker 4096 Sep 29 21:55 .
drwxr-xr-x 17 runner docker 4096 Sep 29 21:55 ..
-rwxr-xr-x  1 runner docker  118 Sep 29 21:55 projen
```

**Comment by jmalins** [comment]
The lay of the land looks like the `build` and `release` modules implement similar GHA functionality without attempting to share much code. As a first stab, I took a similar approach. Please let me know if I should implement something more factored.

**Comment by mrgrain** [comment]
@jmalins The lay of the land is fine. Unless of course you want to refactor, that's always welcome! 😃

**Review by mrgrain — APPROVED** [review]
Decided to merge. You are very welcome to do some refactoring later if you'd like to.

**Comment by mrgrain** [comment]
@jmalins Apologies, but rebasing messed up the snapshots. Would you mind resolving that?

**Pull request merged**
