### PR TITLE
fix(file): annotate generated in sub-project creates incorrect patterns

### LINKED ISSUE #2560: Files in sub-projects are not correctly annotated as generated
When creating any sub-class of `FileBase`, the file is annotated as generated using the `linguist-generated` attribute in `.gitattributes` (see #629).

This is achieved by calling the `annotateGenerated` method on the root project, while passing the path relative to the sub-project.
https://github.com/projen/projen/blob/e236e583070096e933649b35d205c257dcbc0422/src/file.ts#L98-L100

There are two possible ways to fix this issue:
1. Call `annotateGenerated` on the sub-project instead
2. Reconstruct the path relative to the root project

My preference is option 1, and I am currently working on a pull request to make this change. However, I am open to discussion.

### PR DESCRIPTION
**Pull request by dippi**
Closes #2560

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — CHANGES_REQUESTED** [review]
Sounds good. Let's add a test case and this is good to go.

**Comment by dippi** [comment]
I'm not sure where the test should be added:
- to `test/subproject.test.ts`, as the issue is only triggered in subprojects
- to some (or all) test suites regarding the sub-classes of `FileBase`, but it would be spread across multiple files
- to a new test suite for `file.ts`, but `FileBase` is an abstract class so we might need to create a `TestFile` sub-class to be able to instantiate it
- to a new test suite for `github-project`, as it's the only project implementing `annotateGenerated` (in all other cases we could just test `annotateGenerated` to be called, but not the effect on the `.gitattributes` file)

Let me know!

**Comment by mrgrain** [comment]
It doesn't really matter, but I probably would pick `test/subproject.test.ts`

**Review by mrgrain — CHANGES_REQUESTED** [review]
Thanks for the test. They are not wrong, but we prefer a different style here. You can look at  at how the other tests are doing it in the same file.

But basically instead of using spys and mocks, synth the project and inspect the output files.
In your case we'd expect the nested `.gitattributes` in the subproject to include the pattern, and the `.gitattributes` at the root to not include the pattern.

**Comment by dippi** [comment]
That's the issue, `annotateGenerated` is an empty function on `Project`, so there is no `.gitattributes` to inspect. That's why I was hesitant on where to write the test.
https://github.com/projen/projen/blob/7c3fc859c1d22c9d11d486fe80f1d98927fac271/src/project.ts#L536-L545

So I took inspiration from here and used `spyOn`.
https://github.com/projen/projen/blob/e236e583070096e933649b35d205c257dcbc0422/test/javascript/node-package.test.ts#L157-L162

`GitHubProject` has the only implementation, does it make sense for me to use it in this test?
https://github.com/projen/projen/blob/5ecc4165dce59e6d3f89b6e395fa64a9e28e4027/src/github/github-project.ts#L239-L250

**Comment by mrgrain** [comment]
Yes you can use GitHubProject.

**Review by mrgrain — APPROVED** [review]
Excellent! Thanks for implementing my test requirements 🙈😅

**Pull request merged**
