### PR TITLE
fix(pull-request-lint): bump version of GH action amannn/action-semantic-pull-request to v5.4.0; resolves runtime deprecation warnings

### PR DESCRIPTION
**Pull request by icj217**
Used commit hash that corresponds with [v5.4.0](https://github.com/amannn/action-semantic-pull-request/releases/tag/v5.4.0)

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
> Used commit hash that corresponds with [v5.4.0](https://github.com/amannn/action-semantic-pull-request/releases/tag/v5.4.0)
> 
> By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

No you haven't 😂 

No tag here: https://github.com/amannn/action-semantic-pull-request/commit/67cbd7a15a6eeea0c3a0dffff4768fa5653de05c
Tag here: https://github.com/amannn/action-semantic-pull-request/commit/e9fabac35e210fea40ca5b14c0da95a099eff26f

But can we please keep the version number here. I don't think this action requires preemptive action to prevent a malicious tag changes.

**Review by mrgrain — CHANGES_REQUESTED** [review]
Wrong commit, let's keep the version number

**Comment by icj217** [comment]
> > Used commit hash that corresponds with [v5.4.0](https://github.com/amannn/action-semantic-pull-request/releases/tag/v5.4.0)
> > By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> 
> No you haven't 😂
> 
> No tag here: [amannn/action-semantic-pull-request@67cbd7a](https://github.com/amannn/action-semantic-pull-request/commit/67cbd7a15a6eeea0c3a0dffff4768fa5653de05c) Tag here: [amannn/action-semantic-pull-request@e9fabac](https://github.com/amannn/action-semantic-pull-request/commit/e9fabac35e210fea40ca5b14c0da95a099eff26f)
> 
> But can we please keep the version number here. I don't think this action requires preemptive action to prevent a malicious tag changes.

Whoops! Should have said I used a hash that encompasses v5.4.0's changes. Fixed to use version number.

**Comment by mrgrain** [comment]
> Whoops! Should have said I used a hash that encompasses v5.4.0's changes. Fixed to use version number.

Thank you! But for future reference, the phrasing wasn't the problem. You actually do have to use the commit hash the tag is attached to. Using the commit that encompasses the tag will fail.

**Review by mrgrain — APPROVED** [review]

**Comment by mrgrain** [comment]
Approved. You'll need to sync your branch with main and re-run the snapshots.

**Pull request merged**
