### PR TITLE
fix: unit tests failing on Windows

### PR DESCRIPTION
**Pull request by Chriscbr**
There was around 30+ unit tests failing on Windows due to:

- line ending differences between windows and posix
- path separator differences between windows and posix
- echo "foo" would include the quotes in stdout in windows
- paths not being quoted in `exec` calls, causing paths with spaces to get messed up

There are still some tests failing due for other reasons that need to be resolved in follow up pull requests, e.g.: tests that refer to $PWD or the pwd command (some potential fixes are discussed in #452).

Also snapshot tests seem to get deleted after the tests run (not entirely sure why), so I wasn't able to verify if these were getting generated with differences or not.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by eladb — APPROVED** [review]

**Comment by john-tipper** [comment]
Is this still a draft PR or is it good to go please?

**Comment by Chriscbr** [comment]
> Is this still a draft PR or is it good to go please?

This might still be valid, but it was written with a much older version of projen. I'll try update it this weekend.

**Comment by Chriscbr** [comment]
@projen rebuild

**Comment by Chriscbr** [comment]
For whatever reason Windows doesn't like the way we were changing directories before each unit test in `java-project.test.ts` (all of them failed like the screenshot) so in this last commit I just changed the fixture to use the 'outdir' field.

Screenshot 2021-02-26 011929

**Pull request merged**
