### PR TITLE
fix(task-runtime): commands are not working on windows when chained with AND `&&`

### PR DESCRIPTION
**Pull request by gmeligio**
Related to https://github.com/projen/projen/issues/3384

I missed this when reviewing https://github.com/projen/projen/pull/3723. Then, it didn't work when testing locally because `rm` and `mv` don't exist on the cmd shell. I've tested it on a Windows Server 2022 machine, and `rm` and `mv` are unavailable in the cmd shell. It seems Github has something configured in the windows-latest runner so that `rm` and `mv` get executed correctly.

I added support for chaining shx-supported commands with `&&` to be compatible with the `cmd` shell at runtime.

---

<details>
<summary>'rm' is not recognized</summary>

❯ yarn package  
yarn run v1.22.19
$ node ./projen.js package
👾 package | condition: node -e "if (!process.env.CI) process.exit(1)"
👾 package | rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist
'rm' is not recognized as an internal or external command,
operable program or batch file.
👾 Task "package" failed when executing "rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist" (cwd: D:\Workspace\projen)
Failed to execute command: node bin/projen package Error: Command failed: node bin/projen package
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at execCommand (D:\Workspace\projen\projen.js:9:5)
    at Object.<anonymous> (D:\Workspace\projen\projen.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 71416,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</details>

<details>
<summary>'mv' is not recognized</summary>

❯ yarn package  
yarn run v1.22.19
$ node ./projen.js package
👾 package | condition: node -e "if (!process.env.CI) process.exit(1)"
👾 package | rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist
'mv' is not recognized as an internal or external command,
operable program or batch file.
👾 Task "package" failed when executing "rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist" (cwd: D:\Workspace\projen)
Failed to execute command: node bin/projen package Error: Command failed: node bin/projen package
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at execCommand (D:\Workspace\projen\projen.js:9:5)
    at Object.<anonymous> (D:\Workspace\projen\projen.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 71416,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

</details>

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
Hmm. But why isn't this command run though shx in the first place? 🤔

**Comment by gmeligio** [comment]
> Hmm. But why isn't this command run though shx in the first place? 🤔
> 
> This code should take care of that:
> 
> https://github.com/projen/projen/blob/ba5b2d2be69d17cdeb749f1b3d3aaa2a666e20df/src%2Ftask-runtime.ts#L177-L178
> 
> Edit: Ah you've linked the same thing. I reckon we should fix the code that takes care of deciding to call shx or not instead.

The way it's working currently it's that if the command matches the shx supported commands, then `shx` is prepended at build time and persisted in the `tasks.json`. By reading your comment and in other MRs, I think you suppose that `shx` is prepended at runtime.

I'm working on parsing of `&&` to support chained commands in a single command.

**Comment by gmeligio** [comment]
By the way, I like the way it's working actually, because we can trust the command we see in tasks.json and there is no magic in the command when running it, just the plain command. What are your thoughts?

**Comment by gmeligio** [comment]
This is ready for a review @mrgrain.

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
