### PR TITLE
fix: prettier.addOverride was ignored

### PR DESCRIPTION
**Pull request by tinovyatkin**
`prettier.addOverride` was pushing into a temporary array and so effectively ignored. This PR fixes that.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — APPROVED** [review]

**Comment by mrgrain** [comment]
Thanks @tinovyatkin 🎉  

There's an issue with the jsii types here. I think it's enough to remove the `readonly`. You can verify this locally by running `yarn build`.

Would you also mind adding (or extending) a test for it so we don't run into this issue again?

**Review by mrgrain — APPROVED** [review]
🚀

**Comment by tinovyatkin** [comment]
@mrgrain any particular reason we don't to merge it yet or just a forgotten `no-merge` label?

**Comment by mrgrain** [comment]
> @mrgrain any particular reason we don't to merge it yet or just a forgotten `no-merge` label?

Thanks for following up on this. Yep, I just forgot to take of the label 🙈

**Pull request merged**
