### PR TITLE
fix(subprojects)!: conflicting projenDevDependency is added to subprojects by default

### PR DESCRIPTION
**Pull request by timothymathison**
Partially addresses: #3304

BREAKING CHANGE: by default `projen` will not be installed in subproject directories. To install `projen` in a subproject directory, explicitly set `projenDevDependency: true` in the subproject.

Installing projen in sub-projects leads to weird behavior where the sub-project is referencing different source than the parent project - which breaks things like `instanceof` expressions when the two class objects are from different sources. I think it makes more sense to only install a single copy of `projen` for an entire project graph.
I suspect that enabling sub-project installation by default was an oversight originally since it makes sense to have that default for the root project. So I think its safe to consider this a non-breaking change since the default will stay unchanged for a root project.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by timothymathison** [comment]
@mrgrain mind reviewing this when you have a chance?

**Comment by timothymathison** [comment]
> See here for the required format of your PR:
> https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer

In this case, that goes in the PR description (since you generally squash merge) right?

**Comment by mrgrain** [comment]
> > See here for the required format of your PR:
> > https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-both--and-breaking-change-footer
> 
> In this case, that goes in the PR description (since you generally squash merge) right?

Correct PR title and description will make up the commit message.

**Comment by timothymathison** [comment]
Okay, PR description updated, let me know if its satisfactory

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
