### PR TITLE
fix(github): pull-request-lint

### PR DESCRIPTION
**Pull request by kennyg**
- adds githubBaseUrl to allow action to authenticate against github enterprise url

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — CHANGES_REQUESTED** [review]
How about we always set this value to `${{ github.server_url }}`?

**Comment by kennyg** [comment]
> How about we always set this value to `${{ github.server_url }}`?

I can use `${{ github.api_url }}`.  I'll update the PR.

**Review by mrgrain — CHANGES_REQUESTED** [review]

**Comment by mrgrain** [comment]
Looks good now!

**Review by mrgrain — APPROVED** [review]

**Comment by kennyg** [comment]
> Looks good now!

@mrgrain my apologies. I used the wrong variable and didn't notice until I went to this this morning. I used `action_url` when I should have used `api_url`. PR coming up to fix.

**Comment by mrgrain** [comment]
Interesting. It still works on public GitHub. I guess it fails for enterprise?

**Pull request merged**
