### PR TITLE
feat(gitlab): support fallback-keys

### PR DESCRIPTION
**Pull request by ctasada**
Fixes issue #2960

With Gitlab 16.0 a new key was added to the Cache, to support multiple fallback_keys. This value provides some extra benefits over the CACHE_FALLBACK_KEY env variable. See https://docs.gitlab.com/ee/ci/yaml/index.html#cachefallback_keys

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — APPROVED** [review]

**Comment by mrgrain** [comment]
Thanks @ctasada Can your run the build locally to add the mutations to your PR?

**Comment by ctasada** [comment]
@mrgrain I think that now I pushed all the files. Can you confirm?

**Comment by mrgrain** [comment]
> @mrgrain I think that now I pushed all the files. Can you confirm?

I'm re running the build. If it turns green, it will be all good.

**Comment by mrgrain** [comment]
Still one failing, sorry.

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
