### PR TITLE
feat: Caching dependencies in GitHub actions

### PR DESCRIPTION
**Pull request by Dzhuneyt**
Closes https://github.com/projen/projen/issues/1439

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Chriscbr — CHANGES_REQUESTED** [review]
I think this might not be as simple as a one line change. 😉

Could you share how you tested this change? I'd like to understand what this does before we merge it in -- perhaps a comparison between a GitHub workflow run where caching wasn't enabled and one where caching was enabled. 

Caching should also be configurable (so it can be disabled if it's causing problems in a user's project).

It's possible to configure projen projects with a different packager than npm -- we should probably switch the "cache" field value appropriately.

Unit tests? docs?

**Comment by moltar** [comment]
@Dzhuneyt I think the solution needs to set the correct package manager value based on the project

https://github.com/projen/projen/issues/1439#issuecomment-1018251364

Also, I'd make caching opt-in, with maybe defaulting to true?

How about exposing `with.node-version` and `with.architecture` to be able to be set by the user?

**Review by eladb — DISMISSED** [review]

**Comment by Dzhuneyt** [comment]
> I think this might not be as simple as a one line change. 😉
> 
> Could you share how you tested this change? I'd like to understand what this does before we merge it in -- perhaps a comparison between a GitHub workflow run where caching wasn't enabled and one where caching was enabled.
> 
> Caching should also be configurable (so it can be disabled if it's causing problems in a user's project).
> 
> It's possible to configure projen projects with a different packager than npm -- we should probably switch the "cache" field value appropriately.
> 
> Unit tests? docs?

I'm quite familiar with GitHub Actions and the caching part of the "setup-node" action, but...

I have now created two new example repositories, using the "node" template of Projen. I noticed that after my change, the "Release" GitHub workflow starts breaking but the error is quite cryptic and I can't see a clear way forward. It seems to be comparing the GitHub Actions workflow files using a command `release | git diff --ignore-space-at-eol --exit-code
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml`. I don't know what `a` and `b` stand for.

Here's a vanilla repo created with a clean Projen:
https://github.com/dzhuneyt-projen/projen-test-vanilla/actions/runs/1728131880
Here's after my change:
https://github.com/dzhuneyt-projen/projen-test-with-github-caching/runs/4894846708

**Comment by moltar** [comment]
@Dzhuneyt I think these errors are because you haven't updated the projen-managed files. When GH Actions run, they call `projen`, which re-generates the managed files, and then it diffs for changes. If changes were found (git is dirty), then it throws.

When I clone your repo, and install & run projen, I get the following files changed:

screenshot-20220121T181549-4g1ljOy1

**Comment by Dzhuneyt** [comment]
@moltar which command have you ran to see these changes?

**Comment by moltar** [comment]
> @moltar which command have you run to see these changes?

`projen`

**Pull request closed without merging**
