### PR TITLE
feat(tasks): add removeTask method

### PR DESCRIPTION
**Pull request by mmcculloh-dms**
Simple method. Unsure of the general philosophy of projen on whether or not this should throw if you try to delete something that doesn't exist. I went with my personal choice, which is to handle that. I would be happy to change it if needed.

Also, chose `remove` instead of `delete` since `remove` is already used for other methods (e.g. `removeScript`)

Addresses a missing functionality, and was mentioned in #754 as well

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Chriscbr — CHANGES_REQUESTED** [review]
Thanks for the PR! 😄 

re: throwing -- I could see it going either way.  It's also possible we could return the deleted `Task` if a task is found (and return undefined otherwise).

I think it might be useful to add a test case to check the behavior when a task is removed and then re-added.

@eladb should anything be done to handle other components "depending" on particular tasks? ex. the github workflow `build.yml` would fail if the `build` task is removed (since the task's name is inserted as a string). Kind of minor edge case.

**Comment by mmcculloh-dms** [comment]
Thanks @Chriscbr, made some changes to address your feedback.

> It's also possible we could return the deleted Task if a task is found (and return undefined otherwise).

I'm down for that, I think it's more useful than simple boolean.

> should anything be done to handle other components "depending" on particular tasks?

I know this isn't what you were referring to, but you made me realize that this should probably throw when trying to remove a task that another task depends on. Added handling of that as well.

**Review by eladb — APPROVED** [review]
Looks great

**Comment by mmcculloh-dms** [comment]
@Mergifyio update

**Pull request merged**
