### PR TITLE
feat(upgrade): allowing to prepand commands to upgrade via upgrade options

### PR DESCRIPTION
**Pull request by AminFazlMondo**
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by eladb — CHANGES_REQUESTED** [review]
why is this needed?

Can't you just use .prependExec() on the upgrade task?

**Comment by AminFazlMondo** [comment]
Thanks @eladb ,
I wanted to use this in one of my [projects](https://github.com/AminFazlMondo/Lerna-Projen), exactly same as what you describe above.
But the hrere is what I get
```
const project = new NodeProject(....)
let upgradeTask = this.tasks.tryFind('upgrade')
// This return undefined
project.synth()
upgradeTask = this.tasks.tryFind('upgrade')
// This returns the task
upgradeTask?.prependExec(....)
```
But after synth the changes to the task does not get reflected. Would you be able to help me if I am making any mistake?

**Comment by Chriscbr** [comment]
@AminFazlMondo You cannot modify tasks after `project.synth()` is called.

> Can't you just use .prependExec() on the upgrade task?

@eladb It looks like the issue is that `upgrade-dependencies` creates its task during `preSynthesize`... definitely a code smell. Same issue as #1103

**Comment by AminFazlMondo** [comment]
Thanks @Chriscbr

**Pull request closed without merging**
