### PR TITLE
chore: add InternalConsoleOptions enum to VSCode launch config

### PR DESCRIPTION
**Pull request by tlakomy**
As requested in https://github.com/projen/projen/pull/316#discussion_r536107141

### CODE REVIEW

**Comment by tlakomy** [comment]
Not sure why but the build pipeline failed on 'anti-tamper check' and my changes are not suspicious, I swear! 😅

**Review by eladb — APPROVED** [review]

**Comment by Chriscbr** [comment]
@projen rebuild

**Comment by Chriscbr** [comment]
Looks like rebuild is failing... (https://github.com/projen/projen/runs/1501437443)

```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/chore/added-internal-console-option-vscode-launch-config*:refs/remotes/origin/chore/added-internal-console-option-vscode-launch-config* +refs/tags/chore/added-internal-console-option-vscode-launch-config*:refs/tags/chore/added-internal-console-option-vscode-launch-config*
  The process '/usr/bin/git' failed with exit code 1
```

**Review by eladb — APPROVED** [review]

**Comment by eladb** [comment]
@projen rebuild

**Comment by eladb** [comment]
@projen rebuild

**Comment by eladb** [comment]
@projen rebuild

**Pull request merged**
