### PR TITLE
fix(node): some directory separators are still inconsistent between platforms in tasks.json and package.json

### PR DESCRIPTION
**Pull request by gmeligio**
Related to https://github.com/projen/projen/issues/3284#issuecomment-1964163891

This is the second attempt at fixing the directory separator issue for lambda entrypoints, which was started in https://github.com/projen/projen/pull/3387. 

I tried adding unit tests for `renderBundleName`. Unfortunately, this can't be unit-tested now because NodeJS exports the `path` package for the Linux platform instead of Windows at import time and not at runtime.
https://github.com/nodejs/node/blob/f28ccd3941e70a825786eff7e28f59014ac76ac9/lib/path.js#L1546

I tested it locally in an example project, and it looks like it's fixed now.
image

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
@gmeligio I assume this would be tested automatically once we start running builds on Windows?

**Comment by mrgrain** [comment]
@gmeligio For some reason this broke the release: https://github.com/projen/projen/actions/runs/8079532064/job/22074128464#step:6:1035

Are you around to fix this forward? Otherwise I'll just revert the PR and we can try again.

**Comment by gmeligio** [comment]
Sorry. Haven't had the time to look at it. I'll look into it in an hour or so. Go ahead and revert if necessary.

**Comment by mrgrain** [comment]
No worries, turns out it got fixed via #3409

**Pull request merged**
