### PR TITLE
fix: Pin jest dependencies to same version

### LINKED ISSUE #1941: JSII compilation error related to @types/jest
Who else receives this error on a fresh initialized construct-library project using projen?
```
09:01:37 - Starting compilation in watch mode...

[2022-06-18T09:01:40.722] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
node_modules/@sinclair/typebox/typebox.d.ts(237,21): error TS2456: Type alias 'StaticIntersectReduce' circularly references itself.
node_modules/@sinclair/typebox/typebox.d.ts(237,110): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(237,124): error TS2315: Type 'StaticIntersectReduce' is not generic.
node_modules/@sinclair/typebox/typebox.d.ts(256,69): error TS2315: Type 'StaticIntersectReduce' is not generic.
node_modules/@sinclair/typebox/typebox.d.ts(271,105): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(272,98): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(285,40): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(289,44): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(291,40): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(323,128): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(325,128): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(329,64): error TS2574: A rest element type must be an array type.
node_modules/@sinclair/typebox/typebox.d.ts(331,61): error TS2574: A rest element type must be an array type.
node_modules/@types/prettier/index.d.ts(41,54): error TS2315: Type 'IsTuple' is not generic.
node_modules/@types/prettier/index.d.ts(53,6): error TS2456: Type alias 'IsTuple' circularly references itself.
node_modules/@types/prettier/index.d.ts(53,65): error TS2574: A rest element type must be an array type.
node_modules/@types/prettier/index.d.ts(53,84): error TS2315: Type 'IsTuple' is not generic.
node_modules/@types/prettier/index.d.ts(96,5): error TS2589: Type instantiation is excessively deep and possibly infinite.
node_modules/@types/prettier/index.d.ts(131,5): error TS2589: Type instantiation is excessively deep and possibly infinite.
node_modules/@types/prettier/index.d.ts(165,5): error TS2589: Type instantiation is excessively deep and possibly infinite.

09:01:40 - Found 20 errors. Watching for file changes.
```

It seems to be somehow related to the used version of `"@types/jest": "^28.1.2"` .
Tried to downgrade to 27.4.1  but adding `devDeps: ["@types/jest@27.4.1"]  ` to my projen config dir not work. In the resulting package.json there is still version 28.1.2 added.
But using `peerDeps: ["@types/jest@27.4.1"]`  did the trick. And the right version is set in the package.json.

Now I am getting the following error:
```
❯ pj watch
👾 watch | jsii -w --silence-warnings=reserved-word
[2022-06-18T11:19:25.509] [ERROR] jsii/package-info - Unable to find a JSII dependency named "@types/jest" as "27.4.1". If you meant to include a non-JSII dependency, try adding it to bundledDependencies instead.
Error: Error: Unable to locate jsii assembly for "@types/jest". If this module is not jsii-enabled, it must also be declared under bundledDependencies: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]:
```

The only way to make compilation work is, to add `  bundledDeps: ['@types/jest@27.4.1']` to my projen config.

### LINKED ISSUE #1946: Bug: Renovate tries to update @types/jest to non-working version due missing version pinning
Currently https://github.com/projen/projen/blob/52911587e364befb2a47e70b84004e8604f6176e/src/typescript/typescript.ts#L382 doesn't pin version of `@types/jest` as is done for `ts-jest` https://github.com/projen/projen/blob/52911587e364befb2a47e70b84004e8604f6176e/src/typescript/typescript.ts#L431.

This causes now following error:
```
npm ERR! While resolving: ts-jest@27.1.5
npm ERR! Found: @types/jest@28.1.3
npm ERR! node_modules/@types/jest
npm ERR!   dev @types/jest@"^28.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @types/jest@"^27.0.0" from ts-jest@27.1.5
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"^27" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @types/jest@27.5.2
npm ERR! node_modules/@types/jest
npm ERR!   peerOptional @types/jest@"^27.0.0" from ts-jest@27.1.5
npm ERR!   node_modules/ts-jest
npm ERR!     dev ts-jest@"^27" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Solution: Pin also `@types/jest`.

Best would probably be to expect that all 3 (`jest`, `ts-jest` and `@types/jest`) are in same major, that can be defined e.g. for this https://github.com/projen/projen/blob/e366ac025939515a5dec37e95430c8101573026a/src/javascript/jest.ts#L594-L596.

Relates to #1941.

### PR DESCRIPTION
**Pull request by Hi-Fi**
Fixes #1946 
Fixes #1941

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Hi-Fi** [comment]
> Would it be better to pin `ts-jest` only in case of `jsii` project instead of pinning it for all the `typescript` projects

Is there some issue keeping all those 3 related to same version? Those depend also each other's so they need to be in same major. Of course if wanting to pin more specific version this would cause issues, but is there that kind of need?

**Comment by yuth** [comment]
The `@lastest` version of `jest`, `ts-jest` and `@types/jest` should work everywhere. It is problem in case of jsii as the version of typescript that can be used there is `3.9` and I think `ts-jest` now does not support the older `typescript@3.9` iirc

**Comment by Hi-Fi** [comment]
> The `@lastest` version of `jest`, `ts-jest` and `@types/jest` should work everywhere. It is problem in case of jsii as the version of typescript that can be used there is `3.9` and I think `ts-jest` now does not support the older `typescript@3.9` iirc

If you check the code, latest was never used unless explicitly stated for jest. So that part is just documentation aligned with functionality. With all latest issue wouldn't have arised. 

Also the fix was made for newer issue, and if older one is not fixed by this, I can remove reference to that.

**Comment by yuth** [comment]
> If you check the code, latest was never used unless explicitly stated for jest

Exactly. Pinning the version probably was a fix at a point in time. I think keeping the version pinned now would cause more problems as we want the new projects to always use the latest version of the packages which has all the issues/bugs fixed.

I was wondering if it is possible to remove the pinning rather than keeping it as its more trouble than worth it in the future

**Comment by Hi-Fi** [comment]
I didn’t dare to remove that fix, but of course removal would be better
option so that by default there is no version definition. Like
documentation stated.

How about with definition? I think that part is still needed to align
delendencies to work with each other?

**Comment by yuth** [comment]
I can raise a PR after removing the version pinning after running some tests.

**Comment by Hi-Fi** [comment]
@yuth removed pinning by default, probably some project creation testing still needed,

**Comment by Hi-Fi** [comment]
@eladb / @Chriscbr  How this looks? This "mixed" pinning causes issues with us with Renovate, as now jest is not updated by renovate, and ts-jest and @types/jest is tried to push to 28...

**Pull request merged**
