### PR TITLE
feat(github): support `working-directory` on GitHub Actions Workflow Step

### LINKED ISSUE #2185: GitHub Actions Step does not support working-directory option
The Step interface doesn't currently expose an option for `working-directory` on a specific job step (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun).

It appears you can work around it with a hack:

```ts
({
            'name': 'synth cdk8s',
            'working-directory': 'k8s/allenv',
            'run': 'node --version\nyarn install\nnpm run build',
          }) as any,
```

But it would be nice for the `Step` to match the options GitHub has available.

I may take a crack at a PR on this one, depending on free time in this project.

### PR DESCRIPTION
**Pull request by mikejgray**
Overrides a job workingDirectory, matching the GitHub Actions spec.

Closes #2185 

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — CHANGES_REQUESTED** [review]
Hi @mikejgray Thanks for that!

I don't think this is doing anything yet though. You'll at least add it somewhere in here
https://github.com/projen/projen/blob/7bb5312156c213411d65955c9dc055161669a726/src/github/workflows.ts#L279


Also, please add or extend a test case. A snapshot test is fine.

**Comment by mrgrain** [comment]
@mikejgray Looking good now, but you'll need to run `yarn build` once locally to update the API docs.

**Comment by mikejgray** [comment]
@mrgrain Done!

**Review by mrgrain — APPROVED** [review]
🚀

**Pull request merged**
