### PR TITLE
fix: remove deprecated zlib library

### PR DESCRIPTION
**Pull request by gmukul01**
Removing the deprecated `zlib`, as this functionality was folded into node.js core:
https://nodejs.org/docs/latest-v16.x/api/zlib.html#

Also the version being used has broken changes. 
https://github.com/kkaefer/DEPRECATED-node-zlib/issues/18

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by gmukul01** [comment]
Its really strange because it is not breaking on local
image

**Comment by mrgrain** [comment]
We run the build with Node 14. Maybe there a some version compatibility issues with zlib the only got resolved in recent versions?

**Comment by mrgrain** [comment]
Oh it might also be due to this: https://github.com/projen/projen/actions/runs/4653227759/jobs/8233918071

**Comment by gmukul01** [comment]
Yes its failing on 16.13 but passing on 16.14, are we thinking to move to >=16.14 in future ?

**Comment by mrgrain** [comment]
> Yes its failing on 16.13 but passing on 16.14, are we thinking to move to >=16.14 in future ?

Ah cool. In that case I think we can just change it here: https://github.com/projen/projen/blob/main/.projenrc.js#L67
I would welcome a PR for that if you want to speed things up.  😃

**Comment by gmukul01** [comment]
Awesome raised [this](https://github.com/projen/projen/pull/2610) PR

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
