### PR TITLE
fix(nextjs)!: updated `NextJsProject` default options

### PR DESCRIPTION
**Pull request by dkershner6**
Fixes https://github.com/projen/projen/issues/3239

I question eslint and jest (in TS) being off, as Next includes both, but I didn't touch those settings as they are easy to override.  Perhaps this is because the eslint rules are not built.

BREAKING CHANGE: Minimum Node version is now 16.14.0 to match Next 13's minimum node version.  

BREAKING CHANGE: Next.js TSConfig `module` is now `esnext` by default, to preserve previous behavior, set `module` to `CommonJS`.

BREAKING CHANGE: Next.js TSConfig `moduleResolution` is now `BUNDLER` by default, to preserve previous behavior, set `moduleResolution` to `NODE`.

BREAKING CHANGE: Next.js TSConfig `strict` is now set to `true` by default, to preserve previous behavior, set `strict` to `false`.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
FYI this is probably a breaking change.

**Comment by mrgrain** [comment]
> I question eslint and jest (in TS) being off, as Next includes both, but I didn't touch those settings as they are easy to override. Perhaps this is because the eslint rules are not built.

Probably. I am not familiar with this project type at all.

**Comment by dkershner6** [comment]
> Probably. I am not familiar with this project type at all.

Jest should work out of the box (aside from tests being prescribed to be in `src` / `pages`, a la `tsconfig` issues).
I'll create a ticket for the eslint rules, and handle as I am converting some `next` projects.

**Review by mrgrain — CHANGES_REQUESTED** [review]
Happy to accept that as is. Can you just add a section into the PR description about why this is a breaking change and how to revert to the previous behavior is needed.

Example: https://github.com/projen/projen/pull/2997

**Comment by dkershner6** [comment]
> Happy to accept that as is. Can you just add a section into the PR description about why this is a breaking change and how to revert to the previous behavior is needed.
> 
> Example: #2997

This is complete, @mrgrain .

**Comment by mrgrain** [comment]
> This is complete, @mrgrain .

Perfect execution! I'll get that merged after the subproject release.

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
