### PR TITLE
fix(nextjs)!: Only tailwind.config.js/tailwind.js are valid config names

### PR DESCRIPTION
**Pull request by pgollucci**
BREAKING CHANGE: TailwindConfigOptions no longer accepts any fileName

 https://tailwindcss.com/docs/installation
 https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/tailwindcss-intellisense/README.md

### CODE REVIEW

**Comment by pgollucci** [comment]
Extension__Tailwind_CSS_IntelliSense_—_p6m7g8_github_io

They do not agree.  What is in this PR is a subset of this list.

**Review by eladb — COMMENTED** [review]
@Chriscbr thoughts?

**Comment by Chriscbr** [comment]
I'm not really clear on this change -- what is the benefit by restricting the filename to an enum?

Also not sure about the change to using a sample file. I think there could still be value in providing a higher-level API for configuring one's tailwind configuration (e.g. for adding plugins), and if the file isn't managed that would not be possible.

What do you think? @pgollucci

**Comment by pgollucci** [comment]
Oh yeah, SampleFile was just a quick flip.  Definitely in favor of the API.

The point of this PR is not every filename works.  Only select ones.  Which names work actually vary by thing; however, the two above are supported by ALL.

tailwind
postcss
intellinse
...

I'm not tied to this PR don't force it.  I spent the better part of a day debugging why tailwind intellisense didn't work.

My recently stint of nextjs prs is all stemming from that.  The funny part is after you do _ALL_ that, you have to set something in .vscode/settings.json for it to work in react aka strings

```js
  "editor.quickSuggestions": {
    "strings": true
  },
```

un related but recommended to prevent double runs and errors in non css files.
```js
  "css.validate": false,
```

**Review by eladb — CHANGES_REQUESTED** [review]
Tests?

**Comment by eladb** [comment]
Updates?

**Comment by eladb** [comment]
Closing. Reopen when ready to continue

**Pull request closed without merging**
