### PR TITLE
fix(jsii): run workflow setup steps for language jobs

### LINKED ISSUE #1799: Adding npmrc for private registry with workflowBootstrapSteps fails on build.yml / package-js
In reference to #1006, we added the following snippet to our `.projenrc.ts`:

```
const project = new awscdk.AwsCdkConstructLibrary({
  //...
  workflowBootstrapSteps: [
    {
      name: 'Login to GitHub npm registry',
      id: 'npm_auth',
      run: 'echo -e "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> ~/.npmrc',
      env: {
        'NPM_TOKEN': '${{ secrets.NPM_PULL_SECRET }}'
      },
    },
  ],
});
```

This will work  for the initial jobs of the `build.yml` and `release.yml` workflows but will fail on the the following jobs as the `$HOME` directory is not shared between jobs.
Therefore the `Install Dependencies` steps of `build.yml/package-js` and `release.yml/release_npm` workflows/jobs will fail.

Pleas advise if this is a bug or if we are using the wrong API for what we need to do.

### PR DESCRIPTION
**Pull request by asdcamargo**
Fix #1799 #1006

Allow workflow setup steps to be used by extensions of node-project. 

This change will enable for example a step that sets NPM authentication for private repos before build and publish.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
@mergifyio rebase

**Review by mrgrain — APPROVED** [review]

**Comment by cplee** [comment]
This change breaks the workaround in #2094 ... if I use the following to get access to Docker socket from the build job, it is also adding these steps to the package jobs which don't use the superchain image.

```workflowBootstrapSteps: [
    {
      name: 'Change permissions on /var/run/docker.sock',
      run: 'sudo chown superchain /var/run/docker.sock',
    },
  ],
```

**Comment by kaizencc** [comment]
@cplee sorry I'm late to the party! But yes, it does. I think this needs to get reverted and/or exposed as an option and not the default. Will take it up with @mrgrain and arrive at a solution.

**Comment by cplee** [comment]
I worked around the problem by using @mrgrain suggestion here: https://github.com/projen/projen/issues/2094#issuecomment-1378460172

**Pull request merged**
