### PR TITLE
fix: use actions/create-github-app-token when not using permissions option

### PR DESCRIPTION
**Pull request by polothy**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by polothy** [comment]
Was thinking either this change, or make the `GithubCredentials` constructor public so we can configure out own:

https://github.com/projen/projen/blob/16a38f9cb0e64ed4238c6ceaf9a3726d905ea33e/src/github/github-credentials.ts#L82

**Comment by polothy** [comment]
This PR partially fixes https://github.com/projen/projen/issues/3111 because it only conditionally replaced `tibdex/github-app-token`.

**Comment by mrgrain** [comment]
> Was thinking either this change, or make the `GithubCredentials` constructor public so we can configure out own:

You should already be able to do this with one line.

https://projen.io/docs/integrations/github/#actions-versions

**Comment by polothy** [comment]
Oh nice, that worked!

```typescript
project.github?.actions.set(
  "tibdex/github-app-token",
  "actions/create-github-app-token@v1"
);
```

Luckily, the `tokenRef` is identical.

**Pull request closed without merging**
