### PR TITLE
feat(tsconfig): removeInclude/Exclude, deduplication, standard Jest testing pattern handling

### PR DESCRIPTION
**Pull request by dkershner6**
Fixes https://github.com/projen/projen/issues/3213

PS - This should be the last PR for a bit, in case you were worried.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mrgrain — CHANGES_REQUESTED** [review]
The additional helpers are obviously fine, maybe these can be a separate PR?

The additional test setups are a bit controversial, because we already have `testdir` to specify where tests should go and I don't really see why we should allow multiple test locations at the same time.

**Comment by mrgrain** [comment]
> PS - This should be the last PR for a bit, in case you were worried.

I'm worried that this is the last one 😢 Your PRs are most welcome!

**Comment by dkershner6** [comment]
> > PS - This should be the last PR for a bit, in case you were worried.
> 
> I'm worried that this is the last one 😢 Your PRs are most welcome!

Just for a lil bit! I'll be around.

**Comment by dkershner6** [comment]
> The additional helpers are obviously fine, maybe these can be a separate PR?
> 
> The additional test setups are a bit controversial, because we already have `testdir` to specify where tests should go and I don't really see why we should allow multiple test locations at the same time.

We actually already do.

https://github.com/projen/projen/blob/8ca52e8c443d05a0b54a9e851c06a6207a127ac4/package.json#L134

Basically, I am updated tsconfigs to match this, so that if someone DOES put tests there, it won't build them, publish with the package, and such.

This is all pretty easy to control from outside projen source code, so if projen itself does not want to allow more common testing patterns outside of JSII, this doesn't block me at all, but most JS/TS development places tests inside the `src` directory, in my experience, so supporting it makes sense.  I also don't think this should break anything for existing projects, so long as we have implemented correctly.

Your call on this one, if you want me to pare down the PR to only the helpers, happy to do so.

**Comment by mrgrain** [comment]
Ahahaha. _cry sob_

I'll need some time to look at this then.
Would you mind splitting the PR up anyway please? We can get the new methods out at least.

**Comment by mrgrain** [comment]
Closing. Need separate PRs for additional methods and change in defaults.

**Pull request closed without merging**
