### PR TITLE
fix(release): provenance statement not being generated because of missing quotes in YAML

### PR DESCRIPTION
**Pull request by gmeligio**
By looking into [projen in NPM](https://www.npmjs.com/package/projen), I noticed that it didn't have the provenance widget in the page. Then, looking into the [Github action run](https://github.com/projen/projen/actions/runs/7942036715/job/21685009089), I verified that it wasn't generated.

I realized, I made a mistake in [#3300](https://github.com/projen/projen/pull/3330) because the value `true` should be quoted in YAML. 

Before, wrong
```yaml
- name: Release
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: registry.npmjs.org
          NPM_CONFIG_PROVENANCE: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
After, correct
```yaml
- name: Release
        env:
          NPM_DIST_TAG: latest
          NPM_REGISTRY: registry.npmjs.org
          NPM_CONFIG_PROVENANCE: "true"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

I tested this fix in one of my projects and it worked correctly
https://github.com/gmeligio/project-gen/actions/runs/7950505218/job/21702908858#step:10:57

Sorry for the mistake.

## Change 1 NPM_CONFIG_PROVENANCE

1. Add quotes to `"true"` so it's passed as an string to resulting YAML workflow.
2. Update `release.test.ts` with the new value where needed.

##  Change 2 workflowNodeVersion

1. Upgrade workflowNodeVersion to v18.14.2. According to [nodejs.org/dist/index.json](https://nodejs.org/dist/index.json), it's the first version in `18.14.X` that supports provenance statements.
```bash
❯ nvm use 18.14.2
Now using node v18.14.2 (npm v9.5.0)
```

## Future improvements

I received a warning in my downstream project but didn't see it in `projen`
```bash
👾 Received non-string value for environment variable NPM_CONFIG_PROVENANCE. Value will be stringified.
```
This helped me to confirm again the issue, but I was surprised of how come it doesn't show up when running `rm -rf lib && yarn projen` in the projen repository. I haven't investigated that yet, but maybe it would be nice if the message is also shown in the projen repository.

---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mrgrain** [comment]
Ha that's a good one. I think there's an other issue as well though: The available npm version isn't quite up to date. We need npm 9.5.0 as minimum.

**Comment by gmeligio** [comment]
Nice catch! npm 9.5.0 appeared in Node v18.14.2 according to [nodejs.org/dist/index.json](https://nodejs.org/dist/index.json). Currently, `workflowNodeVersion` is `18.14.0`, so it should be a minor change.

**Comment by gmeligio** [comment]
Thank you, @mrgrain, for handling this so fast! Now it works https://www.npmjs.com/package/projen
image

Unfortunately, the npm message doesn't show up in the Github job because it was added in npm [v9.6.2](https://docs.npmjs.com/cli/v9/using-npm/changelog#962-2023-03-14), but that is less important I would say. An example of the message is below.
```bash
npm notice publish Signed provenance statement with source and build information from GitHub Actions
npm notice publish Provenance statement published to transparency log: https://search.sigstore.dev/?logIndex=72248776
```

**Comment by mrgrain** [comment]
Awesome! I think there could be an argument to update the npm version for just this particular job to ensure a recent version is used.

**Pull request merged**
